name: dockerImage
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t react-img-build:$(date +%d-%m-%y)  -f Dockerfile.dev . 

    - name: test the Docker image
      run: docker run -e CI=true -t react-img-build:$(date +%d-%m-%y) npm run test -- --coverage 
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: reactjs-application
        environment_name: Reactjsapplication-env
        version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
        region: ap-southeast-1
        deployment_package: deploy.zip