name: dockerImage
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t react-img-build:$(date +%d-%m-%y)  -f Dockerfile.dev .

      - name: test the Docker image
        run: docker run -e CI=true -t react-img-build:$(date +%d-%m-%y) npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-972549640330
          deployment_package: deploy.zip
